---
name: Build wheels
on:
  workflow_call:
    inputs:
      python-version:
        description: >-
          Python version to build the wheels
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Prepare venv
      run: |
        set -e
        python -m pip install --upgrade pip setuptools wheel
        python -m venv .venv
        echo "PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> ${GITHUB_ENV}

    - name: Install python requirements
      run: pip install -r requirements-dev.txt

    - name: Build QRMI wheels
      run: maturin build --release

    - name: Upload QRMI wheels
      uses: actions/upload-artifact@v6
      with:
        name: qrmi-wheels
        path: target/wheels/qrmi-*.whl
        if-no-files-found: error
