---
name: Unittest the QRMI Python code
on:
  workflow_call:
    inputs:
      python-version:
        description: >-
          Python version to be used to unittest the code
        type: string
        required: true
jobs:
  unittest:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Download QRMI wheels
      uses: actions/download-artifact@v6
      with:
        name: qrmi-wheels

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Prepare venv
      run: |
        set -e
        python -m pip install --upgrade pip setuptools wheel
        python -m venv .venv
        echo "PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> ${GITHUB_ENV}

    - name: Install python requirements
      run: pip install -r requirements-dev.txt

    - name: Install QRMI wheels
      run: pip install qrmi-*.whl

    - name: Unittest with pytest
      run: pytest -v ./python

